name: 'tauri-setup'
description: 'Sets up tauri dependencies'
inputs:
  linux:
    required: false
    default: 'false'
    description: "Whether action is run on linux"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - uses: dtolnay/rust-toolchain@stable
    - uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'
    - name: install dependencies (ubuntu only)
      if: ${{ inputs.linux == 'true' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      shell: bash
    - run: npm ci
      shell: bash
